# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 716d346d0e5f042e461890fb661138a1394d6a50737f37b45fe9a2bec1e068301602cf2fd46bc04c2a18de9eb3d6b148dcd77c33fa3c5eebc43571dff49b68b7

test:
  secret_key_base: 76f5ba0c88a177b49eee0330eb095228f5deb5e186ab4d6b16889584bacd8b578b9f0ccebbb2f9ea9ae51add4a33fbd128cf7b21b6a3966ea546097348db4cd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
